trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@2
    inputs:
      version: '16.x'

  - script: npm install
    displayName: 'Instalar dependencias'

  - script: npm run build
    displayName: 'Compilar el proyecto'

  - script: npm test
    displayName: 'Ejecutar pruebas'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'dist'
      artifactName: 'drop'
